import type {
  AccelerationUnit,
  AmountOfSubstanceUnit,
  AreaUnit,
  CapacitanceUnit,
  ChargeUnit,
  ConductanceUnit,
  ConductivityUnit,
  CurrentUnit,
  DensityUnit,
  EnergyUnit,
  ForceUnit,
  FrequencyUnit,
  InductanceUnit,
  LengthUnit,
  LuminousIntensityUnit,
  MagneticFluxDensityUnit,
  MagneticFluxUnit,
  MassUnit,
  PowerUnit,
  PressureUnit,
  ResistanceUnit,
  TemperatureUnit,
  TimeUnit,
  VelocityUnit,
  VoltageUnit,
  VolumeUnit
} from '../units';
import {allUnits} from '../units';
import {ResistivityUnit} from '../units/resistivity';

export type AllDimensions = {
  acceleration: AccelerationUnit,
  amountOfSubstance: AmountOfSubstanceUnit,
  area: AreaUnit,
  capacitance: CapacitanceUnit,
  charge: ChargeUnit,
  conductance: ConductanceUnit,
  conductivity: ConductivityUnit,
  current: CurrentUnit,
  density: DensityUnit,
  energy: EnergyUnit,
  force: ForceUnit,
  frequency: FrequencyUnit,
  inductance: InductanceUnit,
  length: LengthUnit,
  luminousIntensity: LuminousIntensityUnit,
  magneticFlux: MagneticFluxUnit,
  magneticFluxDensity: MagneticFluxDensityUnit,
  mass: MassUnit,
  power: PowerUnit,
  pressure: PressureUnit,
  resistance: ResistanceUnit,
  resistivity: ResistivityUnit,
  temperature: TemperatureUnit,
  time: TimeUnit,
  velocity: VelocityUnit,
  voltage: VoltageUnit,
  volume: VolumeUnit,
};

export type DimensionName = keyof typeof allUnits;