name: Publish npm package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Check for changes in package.json
        id: check_changes
        run: echo "::set-output name=changes::$(git diff --name-only $(git rev-parse FETCH_HEAD) $(git rev-parse HEAD) | grep 'package.json' | wc -l)"

      - name: Publish package
        if: steps.check_changes.outputs.changes == '1'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
